fuel_data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('upload/', views.upload_file, name='upload_file'),
    path('fuel-records/', views.display_fuel_records, name='fuel_records'),
    # path('filter_fuel_records/', views.filter_fuel_records, name='filter_fuel_records'),
    path('logout/', views.logout_view, name='logout'),
    # path('admin/', views.the_admin, )
    path('change_fuel_records/', views.change_fuel_records, name='change_fuel_records'),
    path('update_status', views.update_status, name="update_status")
]

fuel_invoice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_fuel_invoice/', views.create_invoice, name='create_fuel_invoice'),
    path('view_fuel_invoice/', views.invoice_list, name='invoice_list'),
    path('view_fuel_invoice/<invoice_no>', views.invoice_detail, name='invoice_detail'),
    path('delete_invoice/', views.delete_invoice, name='delete_invoice'),
    path('update_invoice_paid_date/', views.update_invoice_paid_date, name='update_invoice_paid_date')   
]


fuel_processing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticator.urls')),
    path('', include('fuel_data.urls')),
    path('', include('fuel_invoice.urls'))
]

fuel_invoice/models.py
from django.db import models

# Create your models here.
class FuelInvoice(models.Model):
    invoice_number = models.CharField(max_length=100, unique=True)
    invoice_date = models.DateField()
    recived_date = models.DateField()
    payment_date = models.DateField(blank=True, null=True)
    related_month = models.IntegerField(default=12)
    related_year = models.IntegerField(default=2024)

    # Quantity
    petrol_92_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    petrol_95_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True) 
    euro_3_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    disel_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    x_mile_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    super_disel_quantity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)


    # RATE
    petrol_92_rate = models.DecimalField(max_digits=5, decimal_places=2)
    petrol_95_rate = models.DecimalField(max_digits=5, decimal_places=2) 
    euro_3_rate = models.DecimalField(max_digits=5, decimal_places=2)
    disel_rate = models.DecimalField(max_digits=5, decimal_places=2)
    x_mile_rate = models.DecimalField(max_digits=5, decimal_places=2)
    super_disel_rate = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.invoice_number}"

fuel_invoice/forms.py
from django import forms
import datetime

# widget=forms.TextInput(attrs={'placeholder': 'Search'}))


class InvoiceForm(forms.Form):

    months = (
        ("1", "January"),
        ("2", "February"),
        ("3", "March"),
        ("4", "April"),
        ("5", "May"),
        ("6", "June"),
        ("7", "July"),
        ("8", "August"),
        ("9", "September"),
        ("10", "October"),
        ("11", "November"),
        ("12", "December")
    )



    years = (
        ("2024", "2024"),
        ("2025", "2025"),
        ("2026", "2026"),
        ("2027", "2027"),
        ("2028", "2028"),
        ("2029", "2029"),
        ("2035", "2035"),
    )

    invoice_number = forms.CharField(max_length=100, required=True)
    invoice_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'placeholder': "YYYY-MM-DD"}))
    recived_date = forms.DateField(initial=datetime.date.today, required=True, widget=forms.DateInput(attrs={'placeholder': "YYYY-MM-DD"}))
    payment_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'placeholder': "YYYY-MM-DD"}))

    # Quantity
    petrol_92_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    petrol_92_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
 
    petrol_95_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    petrol_95_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)

    euro_3_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    euro_3_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)

    disel_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    disel_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)

    x_mile_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    x_mile_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)

    super_disel_rate = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput(attrs={'placeholder': 'With VAT'}))
    super_disel_quantity = forms.DecimalField(max_digits=10, decimal_places=2, required=False)

    related_month = forms.ChoiceField(choices=months, required=True)
    related_year = forms.ChoiceField(choices=years, required=True)

fuel_invoice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import FuelInvoice
from .forms import InvoiceForm
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.decorators import login_required
import json


def days_between(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)


@login_required(login_url='/')
def create_invoice(request):
    """
    View to create a new fuel invoice record.
    """
    if request.method == 'POST' and request.user.has_perm('fuel_invoice.add_fuel_invoice'):
        form = InvoiceForm(request.POST)
        if form.is_valid():
            # Save form data to the FuelInvoice model
            data = form.cleaned_data
            try:
                invoice = FuelInvoice.objects.create(
                    invoice_number=data['invoice_number'],
                    invoice_date=data['invoice_date'],
                    recived_date=data['recived_date'],
                    payment_date=data.get('payment_date'),
                    related_month = data.get('related_month'),
                    related_year = data.get('related_year'),


                    # Quantities
                    petrol_92_quantity=data.get('petrol_92_quantity'),
                    petrol_95_quantity=data.get('petrol_95_quantity'),
                    euro_3_quantity=data.get('euro_3_quantity'),
                    disel_quantity=data.get('disel_quantity'),
                    x_mile_quantity=data.get('x_mile_quantity'),
                    super_disel_quantity=data.get('super_disel_quantity'),

                    # Rates
                    petrol_92_rate=data['petrol_92_rate'],
                    petrol_95_rate=data['petrol_95_rate'],
                    euro_3_rate=data['euro_3_rate'],
                    disel_rate=data['disel_rate'],
                    x_mile_rate=data['x_mile_rate'],
                    super_disel_rate=data['super_disel_rate'],
                )
                messages.success(request, f"Invoice {invoice.invoice_number} created successfully!")
                return redirect('invoice_list')  # Replace with the name of your invoice list view
            except Exception as e:
                print(str(e))
                messages.error(request, f"Error creating invoice: {str(e)}")
    else:
        form = InvoiceForm()
    
    return render(request, 'create_fuel_invoice.html', {'form': form})



@login_required(login_url='/')
def invoice_list(request):
    """
    View to list all fuel invoices.
    """
    invoices = FuelInvoice.objects.all()

    

    updated_invoices = []

    for invoice in invoices:
        tmp_invoice = {
        'invoice_number': "",
        'recived_to_pml': 0,
        'paid_within': 0,
        'invoice_total': 0.0,
        'vat': 0.0,
        'with_vat': 0.0
    }

        total = 0
        recived_to_pml = days_between(str(invoice.recived_date), str(invoice.invoice_date))
        
        paid_within = "Not paid yet"
        if(invoice.payment_date):
            paid_within = days_between(str(invoice.payment_date), str(invoice.recived_date))


        
        if(invoice.petrol_92_quantity):
            total += float(invoice.petrol_92_quantity) * float(invoice.petrol_92_rate)
        
        if(invoice.petrol_95_quantity):
            total += float(invoice.petrol_95_quantity) * float(invoice.petrol_95_rate)

        if(invoice.euro_3_quantity):
            total += float(invoice.euro_3_quantity) * float(invoice.euro_3_rate)
        
        if(invoice.disel_quantity):
            total += float(invoice.disel_quantity) * float(invoice.disel_rate)

        if(invoice.x_mile_quantity):
            total += float(invoice.x_mile_quantity) * float(invoice.x_mile_rate)

        if(invoice.super_disel_quantity):
            total += float(invoice.super_disel_quantity) * float(invoice.super_disel_rate)


        
        without_vat_total = total / 118 * 100
        vat = total - without_vat_total

        tmp_invoice.update({
            'invoice_number': invoice.invoice_number,
            'recived_to_pml': recived_to_pml,
            'paid_within': paid_within,
            'invoice_total': '{:,}'.format(round(without_vat_total, 2)),
            'vat': '{:,}'.format(round(vat, 2)),
            'with_vat': '{:,}'.format(round(total, 2))
        })


        updated_invoices.insert(0, tmp_invoice)

    return render(request, 'view_fuel_invoice.html', {'invoices': updated_invoices})


@login_required(login_url='/')
def invoice_detail(request, invoice_no):
    """
    View to display details of a specific invoice.
    """
    invoice = get_object_or_404(FuelInvoice, invoice_number=invoice_no)

    total = 0
    recived_to_pml = days_between(str(invoice.recived_date), str(invoice.invoice_date))
        
    paid_within = "Not paid yet"
    if(invoice.payment_date):
        paid_within = days_between(str(invoice.payment_date), str(invoice.recived_date))

    
    # VARIABLES
    petrol_92_total = 0.0
    petrol_95_total = 0.0
    euro_3_total = 0.0
    disel_total = 0.0
    x_mile_total = 0.0
    super_disel_total = 0.0



    if(invoice.petrol_92_quantity):
            total += float(invoice.petrol_92_quantity) * float(invoice.petrol_92_rate)
            petrol_92_total = float(invoice.petrol_92_quantity) * float(invoice.petrol_92_rate)
        
    if(invoice.petrol_95_quantity):
        total += float(invoice.petrol_95_quantity) * float(invoice.petrol_95_rate)
        petrol_95_total = float(invoice.petrol_95_quantity) * float(invoice.petrol_95_rate)

    if(invoice.euro_3_quantity):
        total += float(invoice.euro_3_quantity) * float(invoice.euro_3_rate)
        euro_3_total = float(invoice.euro_3_quantity) * float(invoice.euro_3_rate)
        
    if(invoice.disel_quantity):
        total += float(invoice.disel_quantity) * float(invoice.disel_rate)
        disel_total = float(invoice.disel_quantity) * float(invoice.disel_rate)
    

    if(invoice.x_mile_quantity):
        total += float(invoice.x_mile_quantity) * float(invoice.x_mile_rate)
        x_mile_total = float(invoice.x_mile_quantity) * float(invoice.x_mile_rate)

    if(invoice.super_disel_quantity):
        total += float(invoice.super_disel_quantity) * float(invoice.super_disel_rate)
        super_disel_total = float(invoice.super_disel_quantity) * float(invoice.super_disel_rate)

    without_vat_total = total / 118 * 100 
    vat = total - without_vat_total
    

    tmp_invoice = {
        'invoice_number': invoice.invoice_number,
        'recived_to_pml': recived_to_pml,
        'paid_within': paid_within,
        'invoice_total': '{:,}'.format(round(without_vat_total, 2)),
        'vat': '{:,}'.format(round(vat, 2)),
        'with_vat': '{:,}'.format(round(total, 2)),
        'recived_date': invoice.recived_date,
        'payment_date': invoice.payment_date,

        'breakdown': {
            'petrol_92_quantity':invoice.petrol_92_quantity,
            'petrol_95_quantity': invoice.petrol_95_quantity,
            'euro_3_quantity':invoice.euro_3_quantity,
            'disel_quantity': invoice.disel_quantity,
            'x_mile_quantity': invoice.x_mile_quantity,
            'super_disel_quantity': invoice.super_disel_quantity,

            'petrol_92_rate': invoice.petrol_92_rate,
            'petrol_95_rate': invoice.petrol_95_rate,
            'euro_3_rate': invoice.euro_3_rate,
            'disel_rate': invoice.disel_rate,
            'x_mile_rate': invoice.x_mile_rate,
            'super_disel_rate': invoice.super_disel_rate,

            'petrol_92_total': '{:,}'.format(round(petrol_92_total, 2)),
            'petrol_95_total': '{:,}'.format(round(petrol_95_total, 2)),
            'euro_3_total': '{:,}'.format(round(euro_3_total, 2)),
            'disel_total': '{:,}'.format(round(disel_total, 2)),
            'x_mile_total': '{:,}'.format(round(x_mile_total, 2)),
            'super_disel_total': '{:,}'.format(round(super_disel_total, 2)),
        }
    }


    print(invoice.disel_quantity)
    print(disel_total)


    # print(type(tmp_invoice['breakdown']['super_disel_total']))

    return render(request, 'view_fuel_invoice_detail.html', {'invoice': tmp_invoice})


@login_required(login_url='/')
def delete_invoice(request):
    post_data = json.loads(request.body.decode("utf-8"))
    invoice_number = post_data["invoice_number"]
    
    if request.method == 'POST' and request.user.has_perm('fuel_invoice.add_fuel_invoice'):
        invoice = get_object_or_404(FuelInvoice, invoice_number=invoice_number)
        invoice.delete()
        return JsonResponse({'success': True })
    return JsonResponse({'success': False })


@login_required(login_url='/')
def update_invoice_paid_date(request):
    if request.method == "POST" and request.user.has_perm('fuel_invoice.add_fuel_invoice'): 
        post_data = json.loads(request.body.decode("utf-8"))
        invoice_number = post_data["invoice_number"]
        paid_date = post_data["paid_date"]

        obj = FuelInvoice.objects.get(invoice_number=invoice_number)
        obj.payment_date = paid_date
        obj.save()
        
        return JsonResponse({'success': True })
    return JsonResponse({'success': False })

fuel_invoice/templates/create_fuel_invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fuel Invoice</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
        .my-container {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-column-gap: 50px;
        }

        input {
            width: 100%;
        }

        .errorlist {
            position: absolute;
            top: 0;
            right: 0;
            color: #fff;
            padding: 0;
            list-style: none;
        }

        .errorlist > li {
            background-color: #DC3545;
            padding: 5px 25px;
        }

        #id_related_month,
        #id_related_year {
            width: 100%;
            height: 35px;
        }
    </style>
</head>
<body>
    {% include 'header.html' %}

    <form method="POST" class="container" style="margin-top: 100px;">
        <h1 class="mb-5 mt-5">Create a Fuel Invoice</h1>
        <div class="my-container">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <button class="btn btn-primary mb-5" type="submit">Create</button>
    </form>



    <script>
        const today = new Date()
        const today_month = today.getMonth() + 1
        const today_year = today.getFullYear()

        document.getElementById('id_related_month').value = today_month
        document.getElementById('id_related_year').value = today_year
    </script>
</body>
</html>

fuel_invoice/templates/view_fuel_invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Fuel Invoice</title>

    <style>
        .the-date:hover {
            transition: 1s;
            transform: scale(1.2);
        }
    </style>
</head>
<body>
    {% include 'header.html' %}
    <div class="mt-5 container">
        <h1 style="margin: 80px 0 30px 0;">Fuel Invoice</h1>
 
    <table class="table table-hover" style="font-size: 14px;">
        <thead>
            <tr>
                <th>Invoice number</th>
                <th>Recived to PML Within</th>
                <th>Paid Within</th>
                <th>Invoice Total</th>
                <th>VAT</th>
                <th>With VAT</th>
            </tr>
        </thead>
        <tbody id="fuel-record-rows">
            {% for invoice in invoices %}
            <tr>
                <td>
                    <a href="/view_fuel_invoice/{{ invoice.invoice_number }}">
                        {{ invoice.invoice_number }}
                    </a>
                </td>
                <td>{{ invoice.recived_to_pml }} Days</td>
                <td style="cursor: pointer;" class="the-date" onclick="update_paid_date('{{ invoice.invoice_number }}')">
                    
                        {{ invoice.paid_within }} {% if invoice.paid_within != "Not paid yet" %} Days {% endif %}
                    
                </td>
                <td>{{ invoice.invoice_total }}</td>
                <td>{{ invoice.vat }}</td>
                <td>{{ invoice.with_vat }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="10">No invoices found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    <script>
        const csrfToken = '{{ csrf_token }}';

       const update_paid_date = (invoice_number) => {
        console.log(invoice_number)
        let paid_date = "";

        if(paid_date = prompt("Enter the paid date (YYYY-MM-DD)")) {
            console.log(paid_date)
            if(paid_date) {
                fetch(`{% url "update_invoice_paid_date" %}`,{
                method: 'POST',
                headers: { 'X-CSRFToken': csrfToken },
                body: JSON.stringify({
                    invoice_number: invoice_number,
                    paid_date: paid_date
                })
            }).then(res => res.json())
            .then(data => {
                if(data.success) {
                    console.log(data.success)
                    window.location = "{% url 'invoice_list' %}"
                }
            })
            }
        }
       }
    </script>
    </div>
    
</body>
</html>

fuel_invoice/templates/view_fuel_invoice_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Fuel Invoice Details</title>

    <style>
        .list-group-item {
            position: static !important;
        }
    </style>
</head>
<body>
    {% include 'header.html' %}

    <div class="container" style="margin-top: 100px;">
        <div class="mb-5" style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
        <h1>Fuel Invoice: {{ invoice.invoice_number }}</h1>

        <ul class="list-group">
            <li class="list-group-item">
                Recived on 
                <strong>
                    {{ invoice.recived_date }}
                </strong>
            </li>
    
    
            {% if invoice.payment_date %}
            <li class="list-group-item">
                Paid on 
                <strong>
                    {{ invoice.payment_date }}
                </strong>
            </li>
            {% endif %}
        </ul>
    </div>
 
    <table class="table table-hover" style="font-size: 14px;">
        <thead>
            <tr>
                <th>Invoice number</th>
                <th>Recived to PML Within</th>
                <th>Paid Within</th>
                <th>Invoice Total</th>
                <th>VAT</th>
                <th>With VAT</th>
            </tr>
        </thead>
        <tbody id="fuel-record-rows">
            <tr>
                <td>{{ invoice.invoice_number }}</td>
                <td>{{ invoice.recived_to_pml }} Days</td>
                <td>{{ invoice.paid_within }} {% if invoice.paid_within != "Not paid yet" %} Days {% endif %}</td>
                <td>{{ invoice.invoice_total }}</td>
                <td>{{ invoice.vat }}</td>
                <td>{{ invoice.with_vat }}</td>
            </tr>
        </tbody>
    </table>


    <table class="table" style="width: 60%;">
        <thead>
          <tr>
            <th scope="col">Fuel</th>
            <th scope="col">Rate</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
          </tr>
        </thead>
        <tbody>
          
        {% if invoice.breakdown.petrol_92_total != '0.0' %}
            <tr>
                <th scope="row">Petrol 92</th>
                <td>{{ invoice.breakdown.petrol_92_rate }}</td>
                <td>{{ invoice.breakdown.petrol_92_quantity }}</td>
                <td>{{ invoice.breakdown.petrol_92_total }}</td>
          </tr>
        {% endif %}

          
        {% if invoice.breakdown.petrol_95_total != '0.0' %}
            <tr>
                <th scope="row">Petrol 95</th>
                <td>{{ invoice.breakdown.petrol_95_rate }}</td>
                <td>{{ invoice.breakdown.petrol_95_quantity }}</td>
                <td>{{ invoice.breakdown.petrol_95_total }}</td>
          </tr>
        {% endif %}


        {% if invoice.breakdown.euro_3_total != '0.0' %}
            <tr>
                <th scope="row">Euro 3</th>
                <td>{{ invoice.breakdown.euro_3_rate }}</td>
                <td>{{ invoice.breakdown.euro_3_quantity }}</td>
                <td>{{ invoice.breakdown.euro_3_total }}</td>
          </tr>
        {% endif %}



        {% if invoice.breakdown.disel_total != '0.0' %}
            <tr>
                <th scope="row">Disel</th>
                <td>{{ invoice.breakdown.disel_rate }}</td>
                <td>{{ invoice.breakdown.disel_quantity }}</td>
                <td>{{ invoice.breakdown.disel_total }}</td>
          </tr>
        {% endif %}



        {% if invoice.breakdown.x_mile_total != '0.0' %}
            <tr>
                <th scope="row">X Mile</th>
                <td>{{ invoice.breakdown.x_mile_rate }}</td>
                <td>{{ invoice.breakdown.x_mile_quantity }}</td>
                <td>{{ invoice.breakdown.x_mile_total }}</td>
          </tr>
        {% endif %}




        {% if invoice.breakdown.super_disel_total != '0.0' %}
            <tr>
                <th scope="row">Super Disel</th>
                <td>{{ invoice.breakdown.super_disel_rate }}</td>
                <td>{{ invoice.breakdown.super_disel_quantity }}</td>
                <td>{{ invoice.breakdown.super_disel_total }}</td>
          </tr>
        {% endif %}

        </tbody>
      </table>

      <button 
        class="btn btn-danger mt-3" 
        id="delete-btn"
        onclick="delete_invoice('{{ invoice.invoice_number }}')"
        >Delete Invoice</button>

    </div>  


    <script>
        const csrfToken = '{{ csrf_token }}';

        const delete_invoice = (invoice_number) => {

            console.log(invoice_number)
            if(confirm("Are you sure?")) {
                fetch(`{% url "delete_invoice" %}`,{
                method: 'POST',
                headers: { 'X-CSRFToken': csrfToken },
                body: JSON.stringify({
                    invoice_number: invoice_number
                })
            }).then(res => res.json())
            .then(data => {
                
                if(data.success) {
                    console.log(data.success)
                    window.location = "{% url 'invoice_list' %}"
                }
            })
            }
        }
    </script>
    
</body>
</html>